apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/sombiryadav77/argocd.git'
    path: manifest
    targetRevision: master	#HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true #if you want to create ns 
    automated:
      selfHeal: true
      prune: true	

